// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceBricks.TestDataTypes.Postgres;

#nullable disable

namespace ServiceBricks.TestDataTypes.Postgres.Migrations
{
    [DbContext(typeof(TestDataTypesPostgresContext))]
    partial class TestDataTypesPostgresContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TestDataTypes")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceBricks.TestDataTypes.EntityFrameworkCore.Test", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TestBool")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TestBoolNull")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TestBoolNullWithMixedValues")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TestBoolNullWithValue")
                        .HasColumnType("boolean");

                    b.Property<byte>("TestByte")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("TestByteArray")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("TestByteArrayNull")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("TestByteArrayNullWithMixedValues")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("TestByteArrayNullWithValue")
                        .HasColumnType("bytea");

                    b.Property<byte?>("TestByteNull")
                        .HasColumnType("smallint");

                    b.Property<byte?>("TestByteNullWithMixedValues")
                        .HasColumnType("smallint");

                    b.Property<byte?>("TestByteNullWithValue")
                        .HasColumnType("smallint");

                    b.Property<char>("TestChar")
                        .HasColumnType("character(1)");

                    b.Property<char?>("TestCharNull")
                        .HasColumnType("character(1)");

                    b.Property<char?>("TestCharNullWithMixedValues")
                        .HasColumnType("character(1)");

                    b.Property<char?>("TestCharNullWithValue")
                        .HasColumnType("character(1)");

                    b.Property<DateOnly>("TestDateOnly")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TestDateOnlyNull")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TestDateOnlyNullWithMixedValues")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TestDateOnlyNullWithValue")
                        .HasColumnType("date");

                    b.Property<DateTime>("TestDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TestDateTimeNull")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TestDateTimeNullWithMixedValues")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TestDateTimeNullWithValue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TestDateTimeOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TestDateTimeOffsetNull")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TestDateTimeOffsetNullWithMixedValues")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TestDateTimeOffsetNullWithValue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TestDecimal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TestDecimalNull")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TestDecimalNullWithMixedValues")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TestDecimalNullWithValue")
                        .HasColumnType("numeric");

                    b.Property<double>("TestDouble")
                        .HasColumnType("double precision");

                    b.Property<double?>("TestDoubleNull")
                        .HasColumnType("double precision");

                    b.Property<double?>("TestDoubleNullWithMixedValues")
                        .HasColumnType("double precision");

                    b.Property<double?>("TestDoubleNullWithValue")
                        .HasColumnType("double precision");

                    b.Property<float>("TestFloat")
                        .HasColumnType("real");

                    b.Property<float?>("TestFloatNull")
                        .HasColumnType("real");

                    b.Property<float?>("TestFloatNullWithMixedValues")
                        .HasColumnType("real");

                    b.Property<float?>("TestFloatNullWithValue")
                        .HasColumnType("real");

                    b.Property<Guid>("TestGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TestGuidNull")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TestGuidNullWithMixedValues")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TestGuidNullWithValue")
                        .HasColumnType("uuid");

                    b.Property<int>("TestInt")
                        .HasColumnType("integer");

                    b.Property<int?>("TestIntNull")
                        .HasColumnType("integer");

                    b.Property<int?>("TestIntNullWithMixedValues")
                        .HasColumnType("integer");

                    b.Property<int?>("TestIntNullWithValue")
                        .HasColumnType("integer");

                    b.Property<long>("TestLong")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestLongNull")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestLongNullWithMixedValues")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestLongNullWithValue")
                        .HasColumnType("bigint");

                    b.Property<short>("TestSbyte")
                        .HasColumnType("smallint");

                    b.Property<short?>("TestSbyteNull")
                        .HasColumnType("smallint");

                    b.Property<short?>("TestSbyteNullWithMixedValues")
                        .HasColumnType("smallint");

                    b.Property<short?>("TestSbyteNullWithValue")
                        .HasColumnType("smallint");

                    b.Property<short>("TestShort")
                        .HasColumnType("smallint");

                    b.Property<short?>("TestShortNull")
                        .HasColumnType("smallint");

                    b.Property<short?>("TestShortNullWithMixedValues")
                        .HasColumnType("smallint");

                    b.Property<short?>("TestShortNullWithValue")
                        .HasColumnType("smallint");

                    b.Property<string>("TestString")
                        .HasColumnType("text");

                    b.Property<string>("TestStringNull")
                        .HasColumnType("text");

                    b.Property<string>("TestStringNullWithMixedValues")
                        .HasColumnType("text");

                    b.Property<string>("TestStringNullWithValue")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("TestTimeOnly")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("TestTimeOnlyNull")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("TestTimeOnlyNullWithMixedValues")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("TestTimeOnlyNullWithValue")
                        .HasColumnType("time without time zone");

                    b.Property<long>("TestTimeSpan")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestTimeSpanNull")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestTimeSpanNullWithMixedValues")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestTimeSpanNullWithValue")
                        .HasColumnType("bigint");

                    b.Property<long>("TestUInt")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestUIntNull")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestUIntNullWithMixedValues")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestUIntNullWithValue")
                        .HasColumnType("bigint");

                    b.Property<int>("TestUShort")
                        .HasColumnType("integer");

                    b.Property<int?>("TestUShortNull")
                        .HasColumnType("integer");

                    b.Property<int?>("TestUShortNullWithMixedValues")
                        .HasColumnType("integer");

                    b.Property<int?>("TestUShortNullWithValue")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("Test", "TestDataTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
