# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test All Projects
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName!~ServiceBricks.Xunit.Integration" -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=\"json,opencover\"
    - name: Merge Test Results to Get Overall Code Coverage
      run: dotnet test src/V1/Tests/ServiceBricks.Storage.EntityFrameworkCore.XunitNet8 --no-build --verbosity normal --filter "FullyQualifiedName!~ServiceBricks.Xunit.Integration" -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=\"json,opencover\" -p:MergeWith="../ServiceBricks.XunitNet8/TestResults/coverage.json"
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Unit Test Coverage
        color: orange
        path: src/V1/Tests/ServiceBricks.Storage.EntityFrameworkCore.XunitNet8/TestResults/coverage.opencover.xml
        gist-filename: servicebricks-codecoverage.json
        gist-id: bdb5c7c570a7a88ffb3efb3505273e34
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }} 
