// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceBricks.TestDataTypes.Sqlite;

#nullable disable

namespace ServiceBricks.TestDataTypes.Sqlite.Migrations
{
    [DbContext(typeof(TestDataTypesSqliteContext))]
    [Migration("20251211125921_TestDataTypesV1")]
    partial class TestDataTypesV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("ServiceBricks.TestDataTypes.EntityFrameworkCore.Test", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CreateDate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("TestBool")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("TestBoolNull")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("TestBoolNullWithMixedValues")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("TestBoolNullWithValue")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TestByte")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TestByteArray")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TestByteArrayNull")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TestByteArrayNullWithMixedValues")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TestByteArrayNullWithValue")
                        .HasColumnType("BLOB");

                    b.Property<byte?>("TestByteNull")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("TestByteNullWithMixedValues")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("TestByteNullWithValue")
                        .HasColumnType("INTEGER");

                    b.Property<char>("TestChar")
                        .HasColumnType("TEXT");

                    b.Property<char?>("TestCharNull")
                        .HasColumnType("TEXT");

                    b.Property<char?>("TestCharNullWithMixedValues")
                        .HasColumnType("TEXT");

                    b.Property<char?>("TestCharNullWithValue")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TestDateOnly")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TestDateOnlyNull")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TestDateOnlyNullWithMixedValues")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TestDateOnlyNullWithValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TestDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TestDateTimeNull")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TestDateTimeNullWithMixedValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TestDateTimeNullWithValue")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TestDateTimeOffset")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TestDateTimeOffsetNull")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TestDateTimeOffsetNullWithMixedValues")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TestDateTimeOffsetNullWithValue")
                        .HasColumnType("BLOB");

                    b.Property<decimal>("TestDecimal")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TestDecimalNull")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TestDecimalNullWithMixedValues")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TestDecimalNullWithValue")
                        .HasColumnType("TEXT");

                    b.Property<double>("TestDouble")
                        .HasColumnType("REAL");

                    b.Property<double?>("TestDoubleNull")
                        .HasColumnType("REAL");

                    b.Property<double?>("TestDoubleNullWithMixedValues")
                        .HasColumnType("REAL");

                    b.Property<double?>("TestDoubleNullWithValue")
                        .HasColumnType("REAL");

                    b.Property<float>("TestFloat")
                        .HasColumnType("REAL");

                    b.Property<float?>("TestFloatNull")
                        .HasColumnType("REAL");

                    b.Property<float?>("TestFloatNullWithMixedValues")
                        .HasColumnType("REAL");

                    b.Property<float?>("TestFloatNullWithValue")
                        .HasColumnType("REAL");

                    b.Property<Guid>("TestGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TestGuidNull")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TestGuidNullWithMixedValues")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TestGuidNullWithValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestInt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestIntNull")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestIntNullWithMixedValues")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestIntNullWithValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TestLong")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TestLongNull")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TestLongNullWithMixedValues")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TestLongNullWithValue")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("TestSbyte")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte?>("TestSbyteNull")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte?>("TestSbyteNullWithMixedValues")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte?>("TestSbyteNullWithValue")
                        .HasColumnType("INTEGER");

                    b.Property<short>("TestShort")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("TestShortNull")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("TestShortNullWithMixedValues")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("TestShortNullWithValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestString")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestStringNull")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestStringNullWithMixedValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestStringNullWithValue")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("TestTimeOnly")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("TestTimeOnlyNull")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("TestTimeOnlyNullWithMixedValues")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("TestTimeOnlyNullWithValue")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TestTimeSpan")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TestTimeSpanNull")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TestTimeSpanNullWithMixedValues")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TestTimeSpanNullWithValue")
                        .HasColumnType("TEXT");

                    b.Property<uint>("TestUInt")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("TestUIntNull")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("TestUIntNullWithMixedValues")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("TestUIntNullWithValue")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("TestUShort")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("TestUShortNull")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("TestUShortNullWithMixedValues")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("TestUShortNullWithValue")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Key");

                    b.ToTable("Test");
                });
#pragma warning restore 612, 618
        }
    }
}
